module.exports = ''
  + ' /*' + '\n'
  + ' * # <%= package.title %>' + '\n'
  + ' * <%= package.repository.url %>' + '\n'
  + ' *' + '\n'
  + ' *' + '\n'
  + ' * Copyright 2014 Contributors' + '\n'
  + ' * Released under the MIT license' + '\n'
  + ' * http://opensource.org/licenses/MIT' + '\n'
  + ' *' + '\n'
  + ' */' + '\n'
;