module.exports = ''
  + ' /*' + '\n'
  + ' * # <%= title %>' + '\n'
  + ' * <%= repository %>' + '\n'
  + ' * <%= url %>' + '\n'
  + ' *' + '\n'
  + ' * Copyright 2014 Contributors' + '\n'
  + ' * Released under the MIT license' + '\n'
  + ' * http://opensource.org/licenses/MIT' + '\n'
  + ' *' + '\n'
  + ' */' + '\n'
;